
from enum import Enum

class EventType(Enum):
    MISSION_STATUS = "MISSION_STATUS"
    LOGS = "LOGS"
    BATTERY_LEVEL = "BATTERY_LEVEL"
    OBJECT_DETECTION = "OBJECT_DETECTION"
    CONNECTION_STATUS = "CONNECTION_STATUS"
    IDENTIFICATION = "IDENTIFICATION_STATUS"
    MAP = "MAP"
